name: data
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./query.sql
      - ./returns.sql
      - ./profits.sql
      - ./pricing.sql
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          sql_connstring: ${{ secrets.FLAT_DQB4S6_CONNSTRING }}
          sql_queryfile: ./query.sql
          downloaded_filename: data.json
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          sql_connstring: ${{ secrets.FLAT_L4FHVR_CONNSTRING }}
          sql_queryfile: ./returns.sql
          downloaded_filename: returns.json
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          sql_connstring: ${{ secrets.FLAT_L4FHVR_CONNSTRING }}
          sql_queryfile: ./profits.sql
          downloaded_filename: profits.json
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          sql_connstring: ${{ secrets.FLAT_L4FHVR_CONNSTRING }}
          sql_queryfile: ./pricing.sql
          downloaded_filename: pricing.json
